--<ScriptOptions statementTerminator=";"/>

CREATE TABLE NOODLES (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		BRAND_ID INTEGER NOT NULL,
		NAME TEXT NOT NULL,
		NET_WEIGHT INTEGER,
		NOODLES_WEIGHT INTEGER,
		STEP_1_ID INTEGER,
		STEP_2_ID INTEGER,
		STEP_3_ID INTEGER,
		STEP_4_ID INTEGER,
		SOAKAGE_TIME INTEGER NOT NULL,
		DESCRIPTION TEXT,
		LOGO TEXT
	);

CREATE TABLE MANUFACTURER (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		NAME TEXT NOT NULL,
		LOGO TEXT
	);

CREATE TABLE STEP (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		DESCRIPTION TEXT,
		ICON TEXT
	);

CREATE TABLE BRAND (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		MANUFACTURER_ID INTEGER NOT NULL,
		PARENT_BRAND_ID INTEGER,
		NAME TEXT NOT NULL,
		LOGO TEXT
	);

CREATE TABLE BARCODE (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		CODE TEXT NOT NULL,
		NOODLES_ID INTEGER NOT NULL
	);